### ISSUE TITLE
Error: _uniPublishRemovedHandler is not a function

### ISSUE THREAD

**Issue by MacRusher** [vazco/meteor-universe-collection#17]
Sometimes an error is thrown on the server:

```
I20160725-15:01:25.498(2)? Internal exception while processing message { msg: 'unsub', id: 'XRXHrtHqv4F8RFqgi' } col._uniPublishRemovedHandler is not a function TypeError: col._uniPublishRemovedHandler is not a function
I20160725-15:01:25.501(2)?     at Subscription.removedHandler [as removed] (packages/universe:collection/lib/UniPublish.js:125:16)
I20160725-15:01:25.502(2)?     at packages/ddp-server/livedata_server.js:1148:16
I20160725-15:01:25.502(2)?     at Array.forEach (native)
I20160725-15:01:25.502(2)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20160725-15:01:25.502(2)?     at packages/ddp-server/livedata_server.js:1147:11
I20160725-15:01:25.503(2)?     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
I20160725-15:01:25.503(2)?     at packages/ddp-server/livedata_server.js:1144:9
I20160725-15:01:25.503(2)?     at Object.Meteor._noYieldsAllowed (packages/meteor/fiber_helpers.js:11:1)
I20160725-15:01:25.503(2)?     at Subscription._removeAllDocuments (packages/ddp-server/livedata_server.js:1143:12)
I20160725-15:01:25.503(2)?     at Session._stopSubscription (packages/ddp-server/livedata_server.js:856:30)
```

This probably has something with `UniCollection.publish` and `this.setMappings` which I'm using in the project.

Probably the external collection used in `setMappings` that throws this error is a reference to `UniUsers`

I could provide more code samples on demand.

**Comment by MacRusher** [comment]
There was an issue if one was using `UniPublish` and `this.setMappings` without `PublishAccessMixin`.

Because I don't want to break any logic I've taken safest route and just add a safeguards protecting from calling those functions when they're not defined.

This may also show up in other places so if someone also stumble upon this please open a new issue.
