### ISSUE TITLE
Aggregation doesn't seems to be working with mongodb version 3.6

### ISSUE THREAD

**Issue by rameshbansal** [vazco/meteor-universe-collection#27]
I got following error:

`MongoError: The 'cursor' option is required, except for aggregate with the explain argument
ggrc2
2018-05-24 14:47:05+05:30 at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:449:15)
ggrc2
2018-05-24 14:47:05+05:30 at packages/meteor.js:213:24
ggrc2
2018-05-24 14:47:05+05:30 at UniCollection.aggregate (packages/universe:collection/lib/UniAggregate.js:11:16)
ggrc2
2018-05-24 14:47:05+05:30 at refreshJobUncompletedTasksEarliestDueDate (api/jobs/collection.js:129:28)
ggrc2
2018-05-24 14:47:05+05:30 at [object Object].JobsTasks.methods.updateTaskStatus (api/jobsTasks/methods/updateTaskStatus.js:69:9)
ggrc2
2018-05-24 14:47:05+05:30 at [object Object].<anonymous> (packages/universe:collection/lib/UniHooks.js:166:25)`

**Comment by skyb4ss** [comment]
Based on Mongo documentation: 
MongoDB 3.6 removes the use of aggregate command without the cursor option unless the command includes the explain option. Unless you include the explain option, you must specify the cursor option. 

For more information please visit https://docs.mongodb.com/v3.6/reference/command/aggregate/ or https://stackoverflow.com/questions/49571712/can-aggregate-be-used-in-mongo-3-6-without-cursor
